# Generated by Django 6.0.4 on 2026-09-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('visa_type', models.CharField(choices=[('study', 'Study Visa'), ('visit', 'Visit Visa'), ('work', 'Work Visa')], default='study', max_length=20)),
                ('qualification_level', models.CharField(blank=True, choices=[('undergrad', 'Undergraduate'), ('postgrad', 'Postgraduate'), ('phd', 'PhD / Research')], max_length=20)),
                ('course', models.CharField(blank=True, max_length=150)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='opportunities/')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_hot', models.BooleanField(default=False, help_text='Show this on the landing page as a Hot Opportunity')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]