# Generated by Django 6.1.1 on 2026-09-13 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_university'),
        ('opportunities', '0003_expand_opportunity_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='discipline',
            field=models.ForeignKey(blank=True, help_text="Broad field of study, e.g. 'Business & Management'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='catalog.course'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='qualification_level',
            field=models.CharField(blank=True, choices=[('undergrad', 'Undergraduate'), ('postgrad', 'Postgraduate'), ('phd', 'PhD / Research')], help_text="Shown as 'Level' on the course info panel", max_length=20),
        ),
    ]