# Generated by Django 6.1.1 on 2026-09-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_alter_opportunity_discipline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='logo',
            field=models.ImageField(blank=True, help_text="Shown on the opportunity card instead of the university's default logo", null=True, upload_to='opportunities/logos/'),
        ),
    ]