# Generated by Django 6.1.1 on 2026-09-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0005_opportunity_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='location',
            field=models.CharField(blank=True, help_text="Shown below the university name on the opportunity card, e.g. 'Boston, Massachusetts, USA'. Leave blank to fall back to the university's own location.", max_length=150),
        ),
    ]