# Generated by Django 6.1.1 on 2026-09-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_opportunity_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='university',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='campus',
            field=models.CharField(blank=True, help_text="e.g. 'Main Campus'", max_length=150),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='institute_sector',
            field=models.CharField(blank=True, help_text="e.g. 'Non-Profit'", max_length=100),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='institute_type',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=10),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='university_name',
            field=models.CharField(blank=True, help_text="e.g. 'Harvard University'", max_length=200),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='image',
            field=models.ImageField(blank=True, help_text='Cover photo shown behind the logo on the opportunity card', null=True, upload_to='opportunities/'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='location',
            field=models.CharField(blank=True, help_text="Shown below the university name on the opportunity card, e.g. 'Boston, Massachusetts, USA'", max_length=150),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='logo',
            field=models.ImageField(blank=True, help_text='University logo shown on the opportunity card', null=True, upload_to='opportunities/logos/'),
        ),
    ]