# Generated by Django 6.1.1 on 2026-09-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='countries/')),
                ('description', models.TextField(blank=True)),
                ('universities_count', models.CharField(blank=True, help_text="Shown on the Destinations card, e.g. '150+ Universities'", max_length=50)),
                ('starting_fee', models.CharField(blank=True, help_text="Shown on the Destinations card, e.g. '£12,000+ / year'", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Only active countries appear on the site')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active courses appear on the site')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
