# Generated by Django 6.1.1 on 2026-09-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=210, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='universities/logos/')),
                ('cover_image', models.ImageField(blank=True, help_text='Background photo shown behind the logo on the opportunity card', null=True, upload_to='universities/covers/')),
                ('location', models.CharField(blank=True, help_text="Shown under the university name, e.g. 'Boston, Massachusetts, USA'", max_length=150)),
                ('institute_type', models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
                ('institute_sector', models.CharField(blank=True, help_text="e.g. 'Non-Profit'", max_length=100)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('campus', models.CharField(blank=True, help_text="e.g. 'Main Campus'", max_length=150)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='catalog.country')),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['order', 'name'],
            },
        ),
    ]