# Generated by Django 6.1.1 on 2026-09-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_university'),
        ('opportunities', '0007_remove_opportunity_university_opportunity_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
    ]