# Generated by Django 6.0.4 on 2026-09-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('story', models.TextField()),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube/testimonial video link')),
                ('is_hot', models.BooleanField(default=False, help_text='Feature this on the landing page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
